### PR TITLE
Slng 5 add color to output

### LINKED ISSUE #5: Add colored responses for readability
Definition responses should have colored responses for better readability.

Styling should be similar to python verson:
image

### PR DESCRIPTION
**Pull request by rainrivas**
Fixes #5 
First iteration looks like so
image

Once we finish this, I say we squash it into development

### CODE REVIEW

**Comment by rainrivas** [comment]
@jwu910 I didn't implement everything you had in your screenshot, should I have included for those changes?

**Comment by jwu910** [comment]
I don't think they're necessary. But It does add a little bit of "oooh la la" to the results. Your thoughts? @rainrivas

**Comment by rainrivas** [comment]
@jwu910 not sure.. your python screenshot seems to have more output than mine does. Maybe I need to make some checks into postman and figure out what's up with that

**Comment by jwu910** [comment]
@rainrivas yeah we took some more data from the api response. Your response should carry the same data

**Comment by rainrivas** [comment]
@jwu910 sounds like new issues due to missing features

**Comment by jwu910** [comment]
@rainrivas do you want to add those data points in to the print results now? or just get this out to 1.0.0?

**Review by jwu910 — APPROVED** [review]

**Comment by rainrivas** [comment]
@jwu910 missing features will be added as part of #19 and will be in 1.0. for now we can bump to 2.0 (or can bump soon)

**Pull request merged**
