### PR TITLE
Output help by default - Fix #25

### LINKED ISSUE #25: Show Help by Default
We can probably just reuse the output help cb -- https://www.npmjs.com/package/commander#outputhelpcb

### PR DESCRIPTION
**Pull request by rainrivas**

### CODE REVIEW

**Comment by jwu910** [comment]
image
Are you getting 2 different color outputs when you use the help flag vs no flag?

**Comment by rainrivas** [comment]
> Are you getting 2 different color outputs when you use the help flag vs no flag?

Yeah I saw that. I ran the default help option through a file called "make_red" to make it stand out like, "hey you messed up" but I actually don't know if I like how it looks haha. I'll probably just call help without the color (ln 71 is the line in question)
**EDIT** :: in order to make the help show as just white, we simply need to change line 71 to `program.outputHelp();`

**Comment by jwu910** [comment]
We can also just change 67 and remove `make_red` from `.outputHelp() ` right?

Then we won't need `make_red()`.

**Comment by rainrivas** [comment]
>We can also just change 67 and remove make_red from .outputHelp() right?
Then we won't need make_red().

Yup, i meant to say that we can maket he change on line 67, not 71. If we don't want red help we make that change and golden.

**Comment by jwu910** [comment]
I don't think we need red help. Most progams i've seen if you enter the wrong options or call it w/o any required options, help is displayed white by default anyways

**Review by jwu910 — APPROVED** [review]
LGTM

**Pull request merged**
